server:
  port: 8761
eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 禁用 livereload,否则在同一台机器上启动多个服务时会有端口占用问题
spring:
  devtools:
    livereload:
      enabled: false